### PR TITLE
Use higher of turn degree cost and crossing cost.

### PR DESCRIPTION
**Pull request by dnesbitt61**
Fixes issue #88 
Reduce default maneuver penalty for bicycles.
Also, combine transit operator and block Id into a single int. Reduces structure size to 64 bytes.

### CODE REVIEW

**Comment by dgearhart** [comment]
:shipit:

**Comment by gknisely** [comment]
:bicyclist:

**Comment by gknisely** [comment]
:bike:

**Comment by gknisely** [comment]
:walking:

**Pull request merged**
