### PR TITLE
added logic to avoid ferries via use_ferry flag.  Defaults to 1 (use ferries please)

### PR DESCRIPTION
**Pull request by gknisely**
screenshot from 2016-08-24 10 15 26

screenshot from 2016-08-24 10 16 21

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@meghanhade

**Comment by dnesbitt61** [comment]
Need to alter the A* factor if the ferry weighting factor < walkway factor

**Comment by gknisely** [comment]
closes #130

**Comment by dnesbitt61** [comment]
:shipit:

**Pull request merged**
